application:
  version: "1.0.0"
  name: "kaggle-otto-serving"
  api_prefix: "/v1"
  host: "0.0.0.0"
  port: 8000
  debug: True
  reload: True

retrieval:
  n_past_aid_candidates: 20
  n_covisit_candidates: 10
  n_word2vec_candidates: 10
