version: '3.8'

services:

  db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - kaggle-otto-database:/var/lib/postgresql/data
      - ./project/db:/serving_db

  web:
    build: ./project
    command: ["make", "serve-uvicorn"]
    # command: ["bash"]
    volumes:
      - ./project:/serving
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/web_dev
    depends_on:
      - db

volumes:
  kaggle-otto-database:
